### ISSUE TITLE
Remove "wang" from "-uan" final in minimal pair list

### ISSUE THREAD

**Issue by negativewoman** [helq/pinyin-beginners-anki-deck#10]
In the minimal pair list of "-uan -un -üan", on this [line](https://github.com/helq/pinyin-beginners-anki-deck/blob/327c45b8b11baf63c948681ea9cbb78776442b79/recordings/pairs.json#L86C5-L86C5), "wang1, wang2, wang3, wang4" are mistakenly added as pinyin containing the "-uan" final when they are actually the "-uang" final.

**Comment by helq** [comment]
Thank you @negativewoman for the heads up. I have updated the deck! https://github.com/helq/pinyin-beginners-anki-deck/commit/489ba4f8547b1de3576bd7e5d936d8ef3ea2e115
