### ISSUE TITLE
Card content is not displaying

### ISSUE THREAD

**Issue by Nihisil** [helq/pinyin-beginners-anki-deck#3]
Anki: `Version 2.1.16 (dev)`

Replay plugin is installed and auto-audio play is disabled.

When you click on study you get this error:

```
Invalid HTML on card: ReferenceError: max_sounds_shown is not defined
```

Any ideas how it could be fixed?

**Comment by Nihisil** [comment]
It can be fixed with modifying card template and moving `max_sounds_shown` variable inside a function.

**Comment by helq** [comment]
Hi @Nihisil, thank you for reporting. I have been super busy lately, sorry I couldn't answer you earlier. 

Would you mind making a pull request with the changes. I'll highly appreciate it. If it is not possible, could you upload the new file in a "gist". Thank you :)
