### ISSUE TITLE
Minimal pair does not work on AnkiDroid 2.15.6 - the answer is not shown on the back card

### ISSUE THREAD

**Issue by BorisNA** [helq/pinyin-beginners-anki-deck#9]
The deck (initials, finals) works on ankidroid, but the minmal pair section does not.

The latest AnkDroid  from the GP - 2.15.6 and the latest alpha from github (2.16alpha92). Android 11, google pixel 4a.

The symptom is the same - the front card shows and plays Ok, but the back contains only the copy from the front side and the vowel picture - that's all. The correct answer is not shown at all (unlike in the desktop Anki).

P.S. Tested on the old Android 4.4. - the same. So I think this is something with the new AnkiDroid. Unfortunately, I'm not good with JS and do not understand what happens there with all the persistence etc.

![Screenshot_20230101-214547](https://user-images.githubusercontent.com/7961527/210181755-dd01c4c2-94b9-4acc-93a1-7525d4e50e88.png)

**Comment by BorisNA** [comment]
Well. It looks like one need a separate checkPersistence() function definition on the card back side for Android (different processes, threads, instances - don't know). Testing...

**Comment by BorisNA** [comment]
It appears that the deck was not updated on the Anki site. Since the code here looks to be Ok.

**Comment by helq** [comment]
Hi @BorisNA ! Thanks for letting me know. I'm sorry for being so unresponsive but I was on vacation. Thank you so much for reporting and thank you a lot more for finding a solution!

I noticed there's a new version of anki-persistence. Maybe, they solve the same issue already in their code.

I'll check this bug and I'll reupload the deck this weekend, hopefully.

**Comment by helq** [comment]
Ok, I've checked it (and it took much longer than I expected). It's fixed in the code (at https://github.com/helq/pinyin-beginners-anki-deck/commit/327c45b8b11baf63c948681ea9cbb78776442b79) and in AnkiWeb. Sorry that it took four months :S.
